"""Structural interface: business services accept either database adapter."""
from typing import Protocol


class Repository(Protocol):
    def find(self, kind: str, **query) -> list[dict]: ...
    def insert(self, kind: str, doc: dict) -> dict: ...
    def update(self, kind: str, record_id: str, user_id: str, changes: dict) -> None: ...
    def delete(self, kind: str, record_id: str, user_id: str) -> None: ...
